#!/bin/sh

. /Applications/mampstack-8.0.0-0/scripts/setenv.sh
SASL_PATH="/Applications/mampstack-8.0.0-0/common/lib/sasl2"
                export SASL_PATH
exec /Applications/mampstack-8.0.0-0/common/sbin/.testsaslauthd.bin -f "/Applications/mampstack-8.0.0-0/common/etc/sasldb2" "$@"
